---
name: Windows-2019

on:
  push:
    branches: [argparse-test]
  pull_request:
    branches: [main, release-*]

env:
  ARCH: "x64"
  CC: cl
  CXX: cl

  cplex_DIR: D:\a\cplex

  ZLIB_URL: "https://www.zlib.net/zlib131.zip"


jobs:
  test:
    name: Compile and test planner
    timeout-minutes: 60
    runs-on: ${{ matrix.platform.os }}
    strategy:
      matrix:
        platform:
          - {os: "windows-2019", vc: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Enterprise\\VC\\Auxiliary\\Build\\vcvarsall.bat"}
        python-version: [3.8]
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}


      - name: Compile planner
        shell: cmd
        run: |
          call "${{ matrix.platform.vc }}" %ARCH%
          set CXXFLAGS=/WX
          python build.py release
          python build.py debug

      - name: Install tox
        run: |
          pip3 install tox

      - name: Run translator tests
        shell: cmd
        # We do not run driver tests here because that would require
        # VAL to be installed, which currently cannot be easily done
        # on Windows for the version of VAL we use. When the maintainers
        # of VAL fix the latest version to accept plans without time
        # steps, we hope to be able to install VAL natively on Windows.
        run: |
          call "${{ matrix.platform.vc }}" %ARCH%
          cd misc/
          tox -e translator


...
